### ISSUE TITLE
BE: create API to process orders

### ISSUE THREAD

**Issue by dmgrosu** [dmgrosu/foodmarket#8]
Required functionality:
- fetch all orders for client (by client ID) and period
- fetch order by ID
- create (post) new order for client
- update existing order by ID
- delete order by ID
Controller, service, DAO layers. Tests.

Business logic notes:
1. User can create order, functionally the same as shopping cart
2. User can delete order if not saved (sent to processing)
3. User can place order, sending it to processing
4. User cannot change order after saving
5. User can view own saved orders list for period. List columns: date, total sum, total weight, lines count, state (processed / not processed / erroneous)
6. User can change list pagination and sorting by every column
7. User can view selected order details

**Comment by grosukirill** [comment]
What does _fetch by period_ means? Is that `createdAt` column?
